apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto
data:
  mosquitto.conf: |
    persistence true
    persistence_location /mosquitto/data/
    log_dest stdout
    log_type all
    allow_anonymous true
    listener 1883
    listener 9001
    protocol websockets
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  labels:
    component: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      component: mosquitto
  template:
    metadata:
      labels:
        component: mosquitto
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: mosquitto
          
          image: eclipse-mosquitto:2.0.18-openssl
          ports:
            - containerPort: 1883
              protocol: TCP
              name: mqtt
            - containerPort: 9001
              protocol: TCP
              name: ws
          startupProbe:
            tcpSocket:
              port: 1883
          livenessProbe:
            tcpSocket:
              port: 9001
          command: ["/usr/sbin/mosquitto", "-c", "/mosquitto/config/mosquitto-conf.conf"]
          volumeMounts:
            - name: mosquitto-conf
              mountPath: /mosquitto/config/mosquitto-conf.conf
              subPath: mosquitto.conf
              readOnly: true
          resources:
            limits:
              cpu: 250m
              ephemeral-storage: 512Mi
              memory: 1024Mi
            requests:
              cpu: 125m
              ephemeral-storage: 256Mi
              memory: 512Mi
#      initContainers:
#        - name: config
#          image: busybox:uclibc
#          command:
#            - cp
#           - /tmp/mosquitto.conf
#           - /mosquitto/config/mosquitto.conf
#         volumeMounts:
#           - name: mosquitto-conf
#             mountPath: /tmp/mosquitto.conf
#             subPath: mosquitto.conf
#             readOnly: true
      volumes:
        - name: mosquitto-conf
          configMap:
            name: mosquitto
            items:
              - key: mosquitto.conf
                path: mosquitto.conf
        - name: allowall
          configMap:
            name: postgres-setup
            items:
              - key: allow-all.sh
                path: allow-all.sh
---
apiVersion: v1
kind: Service
metadata:
  name: mqtt
spec:
  ports:
    - port: 1883
      targetPort: 1883
      protocol: TCP
  selector:
    component: mosquitto
---
apiVersion: v1
kind: Service
metadata:
  name: ws
spec:
  ports:
    - port: 9001
      targetPort: 9001
      protocol: TCP
  selector:
    component: mosquitto
