name: MqttSensors
options:
  bundleIdPrefix: at.htl.leonding
  minimumXcodeGenVersion: 2.37.0
packages:
  MQTTNIO:
    url: https://github.com/swift-server-community/mqtt-nio.git
    from: "2.9.0"
  NIOCore:
    url: https://github.com/apple/swift-nio.git
    from: "2.42.0"

targets:
  ThingWorks:
    platform: iOS
    type: application
    deploymentTarget: "16.0"
    sources: [Sources]
    dependencies:
      - package: MQTTNIO
      - package: NIOCore
    embedd: true
    info:
      path: Sources/Info.plist
      properties:
        NSLocationWhenInUseUsageDescription: Aberger wants to use your location
